### ISSUE TITLE
unexpected keyword argument 'method'

### ISSUE THREAD

**Issue by joewilliamsca** [schwark/pyalarmcom#2]
Hey,  just checking out your new python script for alarm.com

It seems if I try to run and of the commands,  I get the following error and stack trace.  Have you seen this before.

Traceback (most recent call last):
  File "alarm.py", line 175, in <module>
    main()
  File "alarm.py", line 171, in main
    print "current status is "+alarm.command(args.operation, args.bypass, args.nodelay, args.silent)
  File "alarm.py", line 133, in command
    panel_id = self._get_panel()
  File "alarm.py", line 80, in _get_panel
    result = self.api_call('systems/availableSystemItems')
  File "alarm.py", line 93, in api_call
    self._login()
  File "alarm.py", line 67, in _login
    data={'__VIEWSTATE': viewstate, '__EVENTVALIDATION': eventval, '__VIEWSTATEGENERATOR': viewstategenerator, 'IsFromNewSite': '1', 'JavaScriptTest': '1', 'ctl00$ContentPlaceHolder1$loginform$hidLoginID': '', 'ctl00$ContentPlaceHolder1$loginform$txtUserName': self.username, 'ctl00$ContentPlaceHolder1$loginform$txtPassword': self.password, 'ctl00$ContentPlaceHolder1$loginform$signInButton': 'Logging In...', 'ctl00$bottom_footer3$ucCLS_ZIP$txtZip': 'Zip Code'}, method='POST')
TypeError: __init__() got an unexpected keyword argument 'method'

**Comment by joewilliamsca** [comment]
Decided not to go this route, closing ticket
